<?php /* Smarty version 2.6.26, created on 2013-02-21 22:11:03
         compiled from menubar_identification.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'translate', 'menubar_identification.tpl', 1, false),array('modifier', 'urlencode', 'menubar_identification.tpl', 45, false),)), $this); ?>
<dt><?php echo Template::mod_translate('Identification'); ?>
</dt>
<dd>
<?php echo ''; ?><?php if (isset ( $this->_tpl_vars['USERNAME'] )): ?><?php echo '<p>'; ?><?php echo Template::mod_translate('Hello'); ?><?php echo ' '; ?><?php echo $this->_tpl_vars['USERNAME']; ?><?php echo ' !</p>'; ?><?php endif; ?><?php echo '<ul>'; ?><?php if (isset ( $this->_tpl_vars['U_REGISTER'] )): ?><?php echo '<li><a href="'; ?><?php echo $this->_tpl_vars['U_REGISTER']; ?><?php echo '" title="'; ?><?php echo Template::mod_translate('Create a new account'); ?><?php echo '" rel="nofollow">'; ?><?php echo Template::mod_translate('Register'); ?><?php echo '</a></li>'; ?><?php endif; ?><?php echo ''; ?><?php if (isset ( $this->_tpl_vars['U_LOGIN'] )): ?><?php echo '<li><a href="'; ?><?php echo $this->_tpl_vars['U_LOGIN']; ?><?php echo '" rel="nofollow">'; ?><?php echo Template::mod_translate('Login'); ?><?php echo '</a></li>'; ?><?php endif; ?><?php echo ''; ?><?php if (isset ( $this->_tpl_vars['U_LOGOUT'] )): ?><?php echo '<li><a href="'; ?><?php echo $this->_tpl_vars['U_LOGOUT']; ?><?php echo '">'; ?><?php echo Template::mod_translate('Logout'); ?><?php echo '</a></li>'; ?><?php endif; ?><?php echo ''; ?><?php if (isset ( $this->_tpl_vars['U_PROFILE'] )): ?><?php echo '<li><a href="'; ?><?php echo $this->_tpl_vars['U_PROFILE']; ?><?php echo '" title="'; ?><?php echo Template::mod_translate('customize the appareance of the gallery'); ?><?php echo '">'; ?><?php echo Template::mod_translate('Customize'); ?><?php echo '</a></li>'; ?><?php endif; ?><?php echo ''; ?><?php if (isset ( $this->_tpl_vars['U_ADMIN'] )): ?><?php echo '<li><a href="'; ?><?php echo $this->_tpl_vars['U_ADMIN']; ?><?php echo '" title="'; ?><?php echo Template::mod_translate('available for administrators only'); ?><?php echo '">'; ?><?php echo Template::mod_translate('Administration'); ?><?php echo '</a></li>'; ?><?php endif; ?><?php echo '</ul>'; ?>

<?php if (isset ( $this->_tpl_vars['U_LOGIN'] )): ?>
<?php echo '<form method="post" action="'; ?><?php echo $this->_tpl_vars['U_LOGIN']; ?><?php echo '" id="quickconnect"><fieldset><legend>'; ?><?php echo Template::mod_translate('Quick connect'); ?><?php echo '</legend><div><label for="username">'; ?><?php echo Template::mod_translate('Username'); ?><?php echo '</label><br><input type="text" name="username" id="username" value="" style="width:99%"></div><div><label for="password">'; ?><?php echo Template::mod_translate('Password'); ?><?php echo '</label><br><input type="password" name="password" id="password" style="width:99%"></div>'; ?><?php if ($this->_tpl_vars['AUTHORIZE_REMEMBERING']): ?><?php echo '<div><label for="remember_me"><input type="checkbox" name="remember_me" id="remember_me" value="1"> '; ?><?php echo Template::mod_translate('Auto login'); ?><?php echo '</label></div>'; ?><?php endif; ?><?php echo '<div><input type="hidden" name="redirect" value="'; ?><?php echo urlencode($_SERVER['REQUEST_URI']); ?><?php echo '"><input type="submit" name="login" value="'; ?><?php echo Template::mod_translate('Submit'); ?><?php echo '"><span class="categoryActions">'; ?><?php if (isset ( $this->_tpl_vars['U_REGISTER'] )): ?><?php echo '<a href="'; ?><?php echo $this->_tpl_vars['U_REGISTER']; ?><?php echo '" title="'; ?><?php echo Template::mod_translate('Create a new account'); ?><?php echo '" class="pwg-state-default pwg-button"><span class="pwg-icon pwg-icon-register"> </span></a>'; ?><?php endif; ?><?php echo '<a href="'; ?><?php echo $this->_tpl_vars['U_LOST_PASSWORD']; ?><?php echo '" title="'; ?><?php echo Template::mod_translate('Forgot your password?'); ?><?php echo '" class="pwg-state-default pwg-button"><span class="pwg-icon pwg-icon-lost-password"> </span></a></span></div></fieldset></form>'; ?>

<?php endif; ?>
</dd>